//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BranchDepartment
    {
        public long ID { get; set; }
        public long BranchID { get; set; }
        public long DepartmentID { get; set; }
        public bool Active { get; set; }
        public System.DateTime CreationDate { get; set; }
        public long CreatedBy { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<System.DateTime> Modified { get; set; }
    
        public virtual Branch Branch { get; set; }
        public virtual Department Department { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
