//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GroupRole
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GroupRole()
        {
            this.ProjectPermissions = new HashSet<ProjectPermission>();
            this.TaskPermissions = new HashSet<TaskPermission>();
        }
    
        public long ID { get; set; }
        public long RoleID { get; set; }
        public long GroupID { get; set; }
        public long CreatedBy { get; set; }
        public System.DateTime CreationDate { get; set; }
    
        public virtual Group Group { get; set; }
        public virtual Role Role { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectPermission> ProjectPermissions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskPermission> TaskPermissions { get; set; }
    }
}
