//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ImpDate
    {
        public long ImpDateID { get; set; }
        public string Notes { get; set; }
        public System.DateTime ImpDate1 { get; set; }
        public Nullable<long> TaskID { get; set; }
        public Nullable<long> ProjectID { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual Task Task { get; set; }
    }
}
