//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Task
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Task()
        {
            this.Approves = new HashSet<Approve>();
            this.ImpDates = new HashSet<ImpDate>();
            this.TaskAttachements = new HashSet<TaskAttachement>();
            this.TaskComments = new HashSet<TaskComment>();
            this.TaskAttachements1 = new HashSet<TaskAttachement>();
            this.TaskHistories = new HashSet<TaskHistory>();
            this.TaskPermissions = new HashSet<TaskPermission>();
        }
    
        public long ID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public string Requirement { get; set; }
        public int PriorityID { get; set; }
        public bool Billable { get; set; }
        public bool TimeTracking { get; set; }
        public bool EApprove { get; set; }
        public Nullable<double> Quality { get; set; }
        public Nullable<double> Time { get; set; }
        public Nullable<double> Performance { get; set; }
        public Nullable<long> CategoryID { get; set; }
        public Nullable<long> ProjectID { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public long CreatedBy { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
        public Nullable<long> SubCategoryprimaryID { get; set; }
        public Nullable<long> SubCategorySecondID { get; set; }
        public bool IsProject { get; set; }
        public Nullable<long> WorkflowID { get; set; }
        public Nullable<int> Revision { get; set; }
        public string status { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<System.DateTime> ReminderDate { get; set; }
        public Nullable<bool> Completed { get; set; }
        public Nullable<System.DateTime> ClosureDate { get; set; }
        public Nullable<System.DateTime> EstimatedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Approve> Approves { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ImpDate> ImpDates { get; set; }
        public virtual Priority Priority { get; set; }
        public virtual Project Project { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskAttachement> TaskAttachements { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskComment> TaskComments { get; set; }
        public virtual TaskCategory TaskCategory { get; set; }
        public virtual TaskPrimarySubCategory TaskPrimarySubCategory { get; set; }
        public virtual TaskSecondarySubCategory TaskSecondarySubCategory { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskAttachement> TaskAttachements1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskHistory> TaskHistories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskPermission> TaskPermissions { get; set; }
    }
}
