//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskCommentAttachment
    {
        public long TaskCommentID { get; set; }
        public string AttachmentPath { get; set; }
        public string FileName { get; set; }
        public string FileExtenssion { get; set; }
        public string Category { get; set; }
        public System.DateTime CreationDate { get; set; }
        public long CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<long> ModifiedBy { get; set; }
    
        public virtual TaskComment TaskComment { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
