//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskPermission
    {
        public int ID { get; set; }
        public Nullable<long> UserRole { get; set; }
        public Nullable<long> GroupRole { get; set; }
        public string Permission { get; set; }
        public long TaskID { get; set; }
    
        public virtual GroupRole GroupRole1 { get; set; }
        public virtual Task Task { get; set; }
        public virtual UserRole UserRole1 { get; set; }
    }
}
