//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskComment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TaskComment()
        {
            this.TaskCommentAttachments = new HashSet<TaskCommentAttachment>();
        }
    
        public long ID { get; set; }
        public string Comment { get; set; }
        public long TaskId { get; set; }
        public long CreatedBy { get; set; }
        public System.DateTime CreationDate { get; set; }
    
        public virtual Task Task { get; set; }
        public virtual TaskAttachement TaskAttachement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TaskCommentAttachment> TaskCommentAttachments { get; set; }
    }
}
