//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskManger.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaskHistory
    {
        public long ID { get; set; }
        public Nullable<long> UserID { get; set; }
        public Nullable<long> TaskID { get; set; }
        public Nullable<long> DelegateTo { get; set; }
        public Nullable<System.DateTime> DelegateDate { get; set; }
        public Nullable<long> ApproveID { get; set; }
    
        public virtual Approve Approve { get; set; }
        public virtual Task Task { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
